### ISSUE TITLE
Mybatis3.3.0 issue

### ISSUE THREAD

**Issue by Kannan85** [mybatis/old-google-code-issues#832]
Hi 

I was using Mybatis 3.2.8 and just migrated to 3.3.0. 

Issue:  In mapper.xml file, we were using the condition ="lastRetryOnDt != null and lastRetryOnDt != &quot;&quot;"> for the Date field lastRetryOnDt  , though it is a wrong thing to check empty quotes for a Date field, it didn't throw any exception in the earlier version 3.2.8. But the newer version 3.3.0, its not allowing and throwing the below exception 

Mybatis validator is not throwing or warning about this. 

Is there any tool or plugin where we can use to validate this in all the Mapper files at compile time? 
its very hard to find these types of issues in the newer version. 

Please help !! 

Exception : 
Error: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
Error updating database.  Cause: java.lang.IllegalArgumentException: invalid comparison: java.util.Date and java.lang.String

Code Snippet:  

"<if test="lastRetryOnDt != null and lastRetryOnDt != &quot;&quot;">
                        DTS.LAST_RETRY_ON_DT = {lastRetryOnDt,jdbcType=TIMESTAMP},      "
                   </if>

**Comment by harawata** [comment]
As stated in README, this repository is not used.
Please post your question to the [mailing list](http://groups.google.com/group/mybatis-user).
